### PR TITLE
Socketio

### PR DESCRIPTION
**Pull request by schnabel**
Hi, 
here is the PR you asked for [here](https://github.com/hifiberry/audiocontrol2/pull/22). The following steps are needed to test the audiocontrol2 PR.

- get-buildroot         ### to apply the patches
- build-config 4       ### I tested on a pi 4 with miniamp
- config 4
   - select gevent, gevent-websocket, socketio
- compile 4
- etc
- copy audiocontrol2 to the pi 
- enable socketio as described [here](https://github.com/schnabel/audiocontrol2/blob/socketio_api/doc/socketio_api.md)

Hope the patch works out for you :-).

### CODE REVIEW

**Comment by pinballpower** [comment]
Did you test the compilation on BR 2021.11? I can get gevent to compile

**Comment by hifiberry** [comment]
Have you been able to compile this? Compilation of gevent breaks here.

**Comment by schnabel** [comment]
Yes, I have been able to compile it. I ran the job with buildroot-2021.05, because you said your not through with migrating to buildroot 2021-11. Can you share the output?

**Comment by schnabel** [comment]
Hi, I did not try it with 2021.11 recently. But if I remember correctly, BR
2021.11 has everything in place for socketio-python.

Am Mo., 7. Feb. 2022 um 10:48 Uhr schrieb pinballpower <
***@***.***>:

**Comment by schnabel** [comment]
I just checked. python-socketio is there but you are right, gevent is not available in neither BR version.

**Comment by hifiberry** [comment]
Gevent is available as a BR package, but I can't get python-gevent to compile

I've uploaded the latest patches to the socketio branch. Can you have a look at this and see how to get it to compile?

**Comment by hifiberry** [comment]
Yes, as we're in the process of migrating to BR 2021.11, the change has to be for 2021.11
(there are still some very old files in your PR, but that's something that can be fixed later)

**Comment by schnabel** [comment]
I can reproduce a build problem with 2021.11:
```
src/gevent/libev/corecext.c: In function ‘__pyx_pymod_exec_corecext’:
src/gevent/libev/corecext.c:24875:36: error: ‘EVBACKEND_IOURING’ undeclared (first use in this function); did you mean ‘EVBACKEND_PORT’?
24875 |   __pyx_t_2 = __Pyx_PyInt_From_int(EVBACKEND_IOURING); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 115, __pyx_L1_error)
      |                                    ^~~~~~~~~~~~~~~~~
      |                                    EVBACKEND_PORT
src/gevent/libev/corecext.c:24875:36: note: each undeclared identifier is reported only once for each function it appears in
```
The reason this occurs is clear.
My patch was for 2021.05! It contains version bumps for a few BR packages (libev etc) because python-gevent depends on these newer versions. Since BR 2021.11 still has the older versions this patch has to be done on 2021.11, too.

Shall I fix this stuff for 2021.11 on my fork?

**Comment by pinballpower** [comment]
Yes, please create a new patch. It's best to create a new patch based on the current development tree. This has been updated with the latest developments for 2021.11

**Comment by hifiberry** [comment]
Yes, please create a new patch. It's best to create a new patch based on the current development tree. This has been updated with the latest developments for 2021.11

**Comment by schnabel** [comment]
Could you be more specific on the 'old files' in my PR you are referring to? I though I only patched BR packages (version bumps on needed packages) and introduced new packages.

**Comment by schnabel** [comment]
Now I have trouble compiling :-(. I created a new branch from development branch. Compiling stops at vollibrespot:
```
   Compiling maybe-uninit v2.0.0
error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed

error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-unknown-linux-gnueabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: build failed
```

Any ideas???

**Comment by hifiberry** [comment]
You need to run get-buildroot again as there is a new patch for Rust in the repo.

**Comment by schnabel** [comment]
Do I have to do a complete build after that? This is so time consuming :-(.

**Comment by schnabel** [comment]
I am a little confused. I think a did get-buildroot after I created the new branch. Could you point me to where the new patch for Rust should be? I would like to confirm that we are on the same page before I start all over agein :-).

**Comment by schnabel** [comment]
I cannot see a such a patch on the development branch. I only see a 2021.11-rc2.patch! Are we talking about the same branch???

**Comment by hifiberry** [comment]
Yes, we're talking about the same branch, but I forgot to check it in ;-) It's there now.

**Comment by schnabel** [comment]
The build went through fine :-) but there is an issue here:
```
>>>   Executing post-image script board/raspberrypi4/post-image.sh
.
.
.
ERROR: vfat(boot.vfat): could not setup rpi-firmware/fixup.dat
make[1]: *** [Makefile:823: target-post-image] Error 1
make: *** [Makefile:84: _all] Error 2
```

I know I have seen this before but I can't remember how to fix it. Do you see the same problem?

**Comment by hifiberry** [comment]
Yes, this is a known problem. Still working on this. Please send your PR based on the current development tree.

**Comment by hifiberry** [comment]
Closing this as the new pull request has been merged.

**Pull request closed without merging**
