### PR TITLE
Re-enable bluetooth HID/HUD plugins

### PR DESCRIPTION
**Pull request by jkp**
Fixes https://github.com/hifiberry/hifiberry-os/issues/480

### CODE REVIEW

**Comment by hifiberry** [comment]
Configuration with HiFIBerryOS64 is changing. Therefore these files don't do anything anymore. I'll add the modules as dependencies to hifiberry-tools.

**Comment by hifiberry** [comment]
It just starts from a default configuration and applies very few settings using configs/override.conf

All packages need to have the correct dependencies which has been fixed in the last months.

**Comment by jkp** [comment]
Interesting. I actually tried to build the latest version of the code yesterday but ran into some `buildroot` issues that seemed to indicate dependency problems. I didn't have the stamina to figure it out...would love to find a way to build the latest code and then perhaps I can make my own image and test it out?

**Comment by hifiberry** [comment]
There's a lot of work right now. Therefore, the development tree is far from stable today. However, it usually should compile. Make sure you download buildroot again with the get-buildroot script as the latest version does require a newer buildroot version than the stable release

**Pull request closed without merging**
