### PR TITLE
hifiberry-shairport, nqptp: change nqptp site, fix string delimiter

### PR DESCRIPTION
**Pull request by soundart**
shairport did not compile for me

### CODE REVIEW

**Comment by hifiberry** [comment]
Please use the provided template for bug reports

**Comment by soundart** [comment]
Hi, sorry which template?

**Comment by hifiberry** [comment]
https://github.com/hifiberry/hifiberry-os/issues/new/choose

**Comment by soundart** [comment]
**Describe the bug**
$ ./compile 3
Secrets file not found, this isn't an official HiFiBerry build
some components might not work as expected
Building in /home/frank/projects/hifiberry-os-and-buildroot/buildroot-3
  GEN     /home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/Makefile
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/package/hifiberry-shairport/Config.in:31:warning: multi-line strings not supported
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/Config.in:48:warning: multi-line strings not supported
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/Config.in:52:warning: multi-line strings not supported
#
# configuration written to /home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/.config
#
Using standard (non package-parallel) build system
/usr/bin/make -j1 O=/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3 HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" syncconfig
  GEN     /home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/Makefile
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/package/hifiberry-shairport/Config.in:31:warning: multi-line strings not supported
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/Config.in:48:warning: multi-line strings not supported
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/Config.in:52:warning: multi-line strings not supported
>>> nqptp 2ffa47e018c9d68a7817148fc42c6074e0b00823 Downloading
--2021-07-26 09:57:10--  https://github.com/hifiberry/nqptp/archive/2ffa47e018c9d68a7817148fc42c6074e0b00823/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 09:57:10 ERROR 404: Not Found.

--2021-07-26 09:57:10--  http://sources.buildroot.net/nqptp/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.0.37, 104.26.1.37, 172.67.72.56, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.0.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 09:57:10 ERROR 404: Not Found.

--2021-07-26 09:57:10--  http://sources.buildroot.net/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 172.67.72.56, 104.26.1.37, 104.26.0.37, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|172.67.72.56|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 09:57:11 ERROR 404: Not Found.

make[1]: *** [package/pkg-generic.mk:148: /home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/build/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823/.stamp_downloaded] Error 1
make: *** [Makefile:84: _all] Error 2


**HiFiBerryOS version**
7f5101c98b2e94ac8f4648a5d066ae421d0018cb

**HiFiBerry sound card**
DAC+ Pro i

**To Reproduce**
./compile 3

**Expected behavior**
no errors

**Screenshots**
**Browser (if applicable)**

**Additional context**

**Comment by hifiberry** [comment]
That looks a bit strange. Did you retrieve and patch the latest buildroot first using get-buildroot?

**Comment by soundart** [comment]
no I build with an old buildroot.:(

I exectuted now get-buildroot and rebuilt. I still have the same issue:

$ ./compile 3
Secrets file not found, this isn't an official HiFiBerry build
some components might not work as expected
Building in /home/frank/projects/hifiberry-os-and-buildroot/buildroot-3
   GEN
/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/Makefile
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/package/hifiberry-shairport/Config.in:31:warning:
multi-line strings not supported
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/Config.in:48:warning:
multi-line strings not supported
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/Config.in:52:warning:
multi-line strings not supported
#
# configuration written to
/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/.config
#
Using standard (non package-parallel) build system
/usr/bin/make -j1
O=/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3
HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" syncconfig
   GEN
/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/Makefile
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/package/hifiberry-shairport/Config.in:31:warning:
multi-line strings not supported
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/Config.in:48:warning:
multi-line strings not supported
/home/frank/projects/hifiberry-os-and-buildroot/hifiberry-os/buildroot/Config.in:52:warning:
multi-line strings not supported
 >>> nqptp 2ffa47e018c9d68a7817148fc42c6074e0b00823 Downloading
wget --passive-ftp -nd -t 3 -O
'/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/build/.nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz.zVti5N/output'
'https://github.com/hifiberry/nqptp/archive/2ffa47e018c9d68a7817148fc42c6074e0b00823/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz'

--2021-07-26 16:34:35--
https://github.com/hifiberry/nqptp/archive/2ffa47e018c9d68a7817148fc42c6074e0b00823/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 16:34:35 ERROR 404: Not Found.

wget --passive-ftp -nd -t 3 -O
'/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/build/.nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz.noeI4G/output'
'http://sources.buildroot.net/nqptp/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz'

--2021-07-26 16:34:35--
http://sources.buildroot.net/nqptp/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.1.37,
172.67.72.56, 104.26.0.37, ...
Connecting to sources.buildroot.net
(sources.buildroot.net)|104.26.1.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 16:34:41 ERROR 404: Not Found.

wget --passive-ftp -nd -t 3 -O
'/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/build/.nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz.f5Ub5B/output'
'http://sources.buildroot.net/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz'

--2021-07-26 16:34:41--
http://sources.buildroot.net/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.0.37,
172.67.72.56, 104.26.1.37, ...
Connecting to sources.buildroot.net
(sources.buildroot.net)|104.26.0.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 16:34:41 ERROR 404: Not Found.

make[1]: *** [package/pkg-generic.mk:148:
/home/frank/projects/hifiberry-os-and-buildroot/buildroot-3/build/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823/.stamp_downloaded]
Error 1
make: *** [Makefile:84: _all] Error 2

**Comment by hifiberry** [comment]
Just pushed a few more changes to Github. Get these and try a fresh build

**Comment by soundart** [comment]
Still the same. Isn't the problem that this:

https://github.com/hifiberry/nqptp/archive/2ffa47e018c9d68a7817148fc42c6074e0b00823/nqptp-2ffa47e018c9d68a7817148fc42c6074e0b00823.tar.gz

does not exist?

It is only visible in the upstream repo where you had the pull request.
Maybe the branch on hifiberry side was deleted?

So if I would want to try airplay-2 it will always fail?

**Comment by hifiberry** [comment]
You're right. After the patch had been merged into the official nqptp repo, I've deleted this. Need to adapt the source tomorrow.

**Comment by hifiberry** [comment]
Ok, this has been fixed now.

**Comment by hifiberry** [comment]
Just noticed that you had the fix prepared already. Just looking at it yesterday it looked like a bug report. Sorry, my mistake.

**Comment by soundart** [comment]
No problem, I now have the correct buildroot version installed :)

**Pull request closed without merging**
