### PR TITLE
patches needed for bottle with socketio

### PR DESCRIPTION
**Pull request by schnabel**

### CODE REVIEW

**Comment by schnabel** [comment]
I have been able to build an image by renaming start4.elf to start.elf and fixup4.dat to fixup.dat. BR has changed some stuff in the processing of the firmware (I guess you know that). The image works :-). I will test the websocket stuff later this afternoon.

**Comment by hifiberry** [comment]
Just building it now with the firmware patch.

**Comment by hifiberry** [comment]
Probably not, but these definitely have to be fixed before we can publish a new release. Still compiling here...

**Comment by hifiberry** [comment]
Merged

**Comment by schnabel** [comment]
Great. Have you been able to test audiocontrol with the socketio client?

**Pull request merged**
